GameFacade = class("GameFacade",PureMVC.Facade)

local module = GameFacade

function module:ctor()
    self.super:ctor()
    --监听命令
    self:RegisterCommand(NotificationNames.START_UP_GAME,function()
        return StartUpCommand.new()
    end)
    self:RegisterCommand(NotificationNames.SHOW_PANEL,function()
        return ShowPanelCommand.new()
    end)
    self:RegisterCommand(NotificationNames.HIDE_PANEL,function()
        return HidePanelCommand.new()
    end)
    self:RegisterCommand(NotificationNames.CHESS_TOUCHED,function()
        return ChessTouchedCommand.new()
    end)
    self:RegisterCommand(NotificationNames.MOVE_CHESS,function()
        return MoveChessCommand.new()
    end)
    self:RegisterCommand(NotificationNames.EAT_CHESS,function()
        return EatChessCommand.new()
    end)
    self:RegisterCommand(NotificationNames.KING_WILL_BE_KILL,function()
        return KingWillBeKillCommand.new()
    end)
    self:RegisterCommand(NotificationNames.DESTROY_PANEL,function()
        return DestroyPanelCommand.new()
    end)
    self:RegisterCommand(NotificationNames.UNDO,function()
        return UndoCommand.new()
    end)
end